backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Type", name: "type", widget: "select", options: ["log", "project"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Summary", name: "summary", widget: "string", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Gallery Images", name: "gallery_images", widget: "list", field: {label: "Image", name: "image", widget: "image"}, required: false}
      - {label: "Project Number (1-4)", name: "project", widget: "list", field: {label: "Project", name: "num", widget: "number"}, required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
